### ISSUE TITLE
Percentage Goes Greater than 100

### ISSUE THREAD

**Issue by martonbaksa** [FormerLurker/ArcWelderPlugin#47] opened 2020-10-27 18:57 UTC
![2020-10-27 14_51_10-Edwidge Danticat, _Children of the Sea_ (1996) (1) pdf](https://user-images.githubusercontent.com/39777617/97348075-097e4b00-1864-11eb-9359-f1efdfae895a.png)

Hi!
I think I might've found a bug. Octoprint doesn't like the file size for some reason, and displays the file size incorrectly (6.2mb instead of 8.1mb actual). This causes the print time and the percentages to break. I've attached the G-Code. 
Marton

GCodes:
[panda_dual_black.zip](https://github.com/FormerLurker/ArcWelderPlugin/files/5447452/panda_dual_black.zip)

**Comment by FormerLurker** [comment] 2020-10-27 22:01
I'm honestly not sure where this issue is coming from.  I don't set the file size anywhere.  I'm wondering if it is added automatically somehow by some other OctoPrint code.  I will look into it.

**Comment by FormerLurker** [comment] 2020-10-27 22:06
So, I'm not seeing what you are seeing when I weld and print this file:

![image](https://user-images.githubusercontent.com/33363128/97367147-99c58b80-1876-11eb-8745-839daa9142a6.png)

It looks like you have a lot of plugins running.  My best guess right now is that it's being caused by some other plugin.  Are you willing to disable them until you figure out which one is causing the problem?  I think that will be the only way to track this down.

**Comment by martonbaksa** [comment] 2020-10-28 02:53
I believe this might have just been a really weird one time error where it didn't get the file size right as deleting the file and manually rewelding it fixed it.

**Comment by FormerLurker** [comment] 2020-10-28 03:48
Interesting.  I wasn't testing with the overwrite option.  It may be some kind of race condition.  I am going to re open this and take a look in the next few days.

**Comment by FormerLurker** [comment] 2020-11-21 19:01
I think this is fixed now.  Will try to release an RC soon.  Resubmit if you see it again!

**Closed as completed by FormerLurker** 2020-11-21 19:01 UTC
Labels: Possible Bug
